# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d773da5e6c92af79974bb7d8da81548cfc0d4c208f1fbaf6d4bc335000b4e746638cd1b2be3893db6269053809788f169cdad3b2bee9a4603817f8ab5014b4cf

test:
  secret_key_base: 098606aac1663e3bb2904878740862858fcdaad3fcd62f457d5a8d5ed5fda6a1438ceee43a50f9f2b3459d732f2e719365b3a121f1315b467c0ea2df4b484b91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
